### ISSUE TITLE
Design a mockup for the UI

### ISSUE THREAD

**Issue by marko-matusovic-personal** [keonchennl/trustchain-superapp#4]
Depends on #3 

Design the views:

 - [x] (fill in from previous issue)

**Comment by MMarko333** [comment]
You can find the design here:
https://miro.com/app/board/uXjVOHWEEAA=/

**Comment by quintene** [comment]
![Library – 1](https://user-images.githubusercontent.com/72068082/158782336-3466da1a-077d-4c0e-8f2b-e7a21413b1fb.png)
![Library](https://user-images.githubusercontent.com/72068082/158782343-60dcef4a-9aa0-4101-b42e-e1e214848c42.png)
![My Literature – 1](https://user-images.githubusercontent.com/72068082/158782344-6a6c0bc0-066f-47f6-9206-447ea7771658.png)
![My Literature](https://user-images.githubusercontent.com/72068082/158782345-51a594d9-832f-4d37-b6d9-ab31ae3606c4.png)
